# Generated by Django 4.1.12 on 2023-10-29 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='inn')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chif_id', models.IntegerField(blank=True, null=True, verbose_name='chif id')),
                ('manager_id', models.IntegerField(blank=True, null=True, verbose_name='manager id')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='position')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('employee', 'Сотрудник')], max_length=20, verbose_name='role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization', verbose_name='organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
