# Generated by Django 4.1.12 on 2023-10-29 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chif_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Подчиненные', to='api.profile', verbose_name='chif'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Менеджер', to='api.profile', verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
