# Generated by Django 4.1.12 on 2023-10-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_chif_id_alter_profile_manager_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='logos/default.png', upload_to='logos/', verbose_name='logo'),
        ),
    ]
